# Generated by Django 5.0.4 on 2024-04-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('start', 'finish')},
        ),
    ]
